services:
  app:
    build:
      dockerfile: ./myplatform/Dockerfile
    command:
      - gunicorn
      - myplatform.wsgi:application
      - -b
      - '0.0.0.0:8000'
    ports:
      - '8000:8000'
    restart: always

#  postgres:
#    image: postgres
