services:
  app:
    build:
      dockerfile: ./myplatform/Dockerfile
    command:
      - gunicorn
      - myplatform.wsgi:application
      - -b
      - '0.0.0.0:8000'
    ports:
      - '8000:8000'
    restart: always

  db_postgres:
    image:
      postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=myplatform_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PG_OPTIONS="--log_destination=stderr --logging_collector=on --log_directory=/var/lib/postgresql/logs/report.log"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d myplatform_db -U admin']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      db_postgres:
        condition: service_healthy

volumes:
  postgres_data:
